### PR TITLE
Add location tag for cash points

### PR DESCRIPTION
**Pull request by makombe**

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks, @makombe. I thought we were to use initialize module for this?

**Comment by makombe** [comment]
Thanks @ojwanganto  Ok, let me add it through config

**Comment by makombe** [comment]
With that guidance, I will close the PR

**Comment by ojwanganto** [comment]
Coming to think of it, may be it is a good idea to have this added through the cashier module. What do you think?

**Pull request closed without merging**
