### PR TITLE
(refactor) KHP3-6492: revert billing of stock items from stock purchase price to use prices…

### PR DESCRIPTION
**Pull request by ojwanganto**
Revert billing of stock items from stock purchase price to use prices set in billables module

https://thepalladiumgroup.atlassian.net/browse/KHP3-6492

### CODE REVIEW

**Review by makombe — APPROVED** [review]
LGTM. Thanks @ojwanganto

**Comment by makombe** [comment]
**DO NOT MERGE**
From the discussion we are likely to release with the old way and this could come later as an enhancement. Cc @ojwanganto @PatrickWaweru @patryllus @njorocs @donaldkibet

**Comment by ojwanganto** [comment]
Can we now have this in? @makombe @Murithijoshua?

**Comment by Murithijoshua** [comment]
@ojwanganto & @makombe this is the proposed way to edit commodities?

**Comment by ojwanganto** [comment]
We prefer this. We just want this merged in once you are done with packaging

**Comment by Murithijoshua** [comment]
@ojwanganto noted.

**Comment by ojwanganto** [comment]
Please note that am having this in to consolidate the changes for testing. Thanks all for the reviews

**Pull request merged**
